### ISSUE TITLE
[Bug]: Actions on Members who left Failing

### ISSUE THREAD

**Issue by 0xEmma** [hackthebox/Hackster#19]
### Describe the bug

When trying to add a note/ban users who have left the server, this action fails

### To reproduce

User leaves server
try to add note / ban / whois / history

### Expected behavior

Note gets added / user gets banned & command should accept INT input

Also should be able to run /whois on an HTB ID, or a user who has left the server, which is not possible.

same with history not allowed to be run on left users

**Comment by 0xEmma** [comment]
From what we had to do previously, iirc its a matter of if `get_user` fails for the guild, just use their UID to insert into the database, or get the user object instead of member object

**Comment by dimoschi** [comment]
@0xEmma so we want to able to ban users who may not be members?

**Comment by 0xEmma** [comment]
Correct, we should be able to ban/pull history/add notes/whois on non-members. This can be useful is several cases and is an _urgent_ issue. 

This is needed because:
- User spams and leaves: cant ban
- User files a ban appeal: unable to pull up history
- User joins on new account, unable to whois or pull history to remove token
- Unable to add note on user who left

**Comment by dimoschi** [comment]
@0xEmma The problem I have to allow both User/Member and id (int value) is that pycord doesn't like it and raises the following error:

```Traceback (most recent call last):
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/cog.py", line 786, in _load_from_module_spec
    setup(self)
  File "/Users/dimos/repos/other/Hackster/src/cmds/core/note.py", line 67, in setup
    bot.add_cog(NoteCog(bot))
  File "/Users/dimos/repos/other/Hackster/src/bot.py", line 97, in add_cog
    super().add_cog(cog, override=override)
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/cog.py", line 656, in add_cog
    cog = cog._inject(self)
          ^^^^^^^^^^^^^^^^^
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/cog.py", line 548, in _inject
    command._set_cog(self)
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/commands/core.py", line 1378, in _set_cog
    subcommand._set_cog(cog)
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/commands/core.py", line 603, in _set_cog
    self.cog = cog
    ^^^^^^^^
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/commands/core.py", line 830, in cog
    self._validate_parameters()
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/commands/core.py", line 708, in _validate_parameters
    self.options: list[Option] = self._parse_options(params)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/commands/core.py", line 739, in _parse_options
    option = Option(option.__args__)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/commands/options.py", line 230, in __init__
    raise exc
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/commands/options.py", line 225, in __init__
    self.input_type = SlashCommandOptionType.from_datatype(input_type)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/enums.py", line 775, in from_datatype
    raise TypeError("Invalid usage of typing.Union")
TypeError: Invalid usage of typing.Union

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dimos/repos/other/Hackster/src/__main__.py", line 12, in <module>
    bot.load_extension(ext)
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/cog.py", line 910, in load_extension
    self._load_from_module_spec(spec, name)
  File "/Users/dimos/repos/other/Hackster/.venv/lib/python3.11/site-packages/discord/cog.py", line 791, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'src.cmds.core.note' raised an error: TypeError: Invalid usage of typing.Union```

In my mind, it would make sense to have both `user` and `user_id` as both options and request the user to provide one or the other, but not both.

**Comment by daanbreur** [comment]
Personally also find that pretty useful. But how does that work with GDPR?

**Comment by 0xEmma** [comment]
> Personally also find that pretty useful. But how does that work with GDPR?

GDPR has no effect with this. We're not storing any PII afaik, this is just standard discord bot functions.

**Comment by daanbreur** [comment]
You are storing the full infraction history together with a user. That is PII.
Even Ubisoft and others have to delete in-game saves after 2 years cause GDPR, and save games really don't have much PII.

**Comment by 0xEmma** [comment]
> You are storing the full infraction history together with a user. That is PII. Even Ubisoft and others have to delete in-game saves after 2 years cause GDPR, and save games really don't have much PII.

Open a separate issue for that, please. This ticket just adds the ability to add/ban data from left users, data is still stored on users who had data attached when joined.

**Comment by daanbreur** [comment]
True, I just was asking about the part of adding to left users. Which you might to think twice about if this really is against GDPR, else this feature is fine and useful

**Comment by 0xEmma** [comment]
> True, I just was asking about the part of adding to left users. Which you might to think twice about if this really is against GDPR, else this feature is fine and useful

As i said, please raise a separate issue for this. While i agree that GDPR can be a concern on users who have left, this PR doesnt change the fact we store infractions on users who have left if that data was added while theyre in the server.
